"""create like/dislik

Revision ID: 1bb8f4552ec6
Revises: 66b8d24dd063
Create Date: 2023-07-22 00:01:19.153484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb8f4552ec6'
down_revision = '66b8d24dd063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###