"""create user

Revision ID: 36153e7545fa
Revises: f2b2fd3bab7a
Create Date: 2023-07-21 19:54:35.660696

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '36153e7545fa'
down_revision = 'f2b2fd3bab7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_table')),
                    sa.UniqueConstraint('email', name=op.f('uq_user_table_email'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    # ### end Alembic commands ###
