"""fix posts -> post

Revision ID: 44165311ef6b
Revises: c5deb5c8f400
Create Date: 2023-07-22 00:29:24.419171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44165311ef6b'
down_revision = 'c5deb5c8f400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###