"""change name author -> author_id post

Revision ID: 453e22f59e51
Revises: d7525c4a2b01
Create Date: 2023-07-21 22:39:40.403885

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '453e22f59e51'
down_revision = 'd7525c4a2b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_post_table_author_user_table', 'post_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_post_table_author_id_user_table'), 'post_table', 'user_table', ['author_id'], ['id'])
    op.drop_column('post_table', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_post_table_author_id_user_table'), 'post_table', type_='foreignkey')
    op.create_foreign_key('fk_post_table_author_user_table', 'post_table', 'user_table', ['author'], ['id'])
    op.drop_column('post_table', 'author_id')
    # ### end Alembic commands ###
