"""add username

Revision ID: 4b3ce14fa03f
Revises: 44165311ef6b
Create Date: 2023-07-22 21:35:15.269318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3ce14fa03f'
down_revision = '44165311ef6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('username', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_table_username'), 'user_table', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_table_username'), 'user_table', type_='unique')
    op.drop_column('user_table', 'username')
    # ### end Alembic commands ###