"""change links

Revision ID: 66b8d24dd063
Revises: 453e22f59e51
Create Date: 2023-07-21 23:29:36.525421

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '66b8d24dd063'
down_revision = '453e22f59e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_table', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_table', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
