"""create post

Revision ID: befd5dd233fa
Revises: 36153e7545fa
Create Date: 2023-07-21 21:47:55.057504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befd5dd233fa'
down_revision = '36153e7545fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###