"""create like/dislik

Revision ID: c5deb5c8f400
Revises: 1bb8f4552ec6
Create Date: 2023-07-22 00:02:13.948328

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c5deb5c8f400'
down_revision = '1bb8f4552ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_table',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.Column('like', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'],
                                            name=op.f('fk_grade_table_post_id_post_table')),
                    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'],
                                            name=op.f('fk_grade_table_user_id_user_table')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_table'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_table')
    # ### end Alembic commands ###
