"""cascade delete

Revision ID: ce6e0f61cd35
Revises: 4b3ce14fa03f
Create Date: 2023-07-23 10:22:26.476991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6e0f61cd35'
down_revision = '4b3ce14fa03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###