"""create user

Revision ID: f2b2fd3bab7a
Revises: 1d49b4e7c496
Create Date: 2023-07-21 19:51:50.822918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b2fd3bab7a'
down_revision = '1d49b4e7c496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###